XRTK/WindowsMixedReality

- XRTK.WindowsMixedReality/Assets/XRTK.WindowsMixedReality/Controllers/WindowsMixedRealityDataProvider.cs
Now the wmr controller data provider raises source found/lost when tracking is found/lost.
> Fixed an issue where there was a 3rd untracked controller in the scene.

- XRTK.WindowsMixedReality/Packages/manifest.json
- XRTK.WindowsMixedReality/ProjectSettings/ProjectVersion.txt
- XRTK.WindowsMixedReality/ProjectSettings/XRSettings.asset
> updated editor to 2019.1

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/SpatialObservers/WindowsMixedRealitySpatialMeshObserver.cs
> we don't need to check if the system exists anymore

- XRTK.WindowsMixedReality/Assets/XRTK.Generated/CustomProfiles/MixedRealityPackageSettings.asset
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Inspectors/WindowsMixedRealityDataProviderProfileInspector.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/package.json
- XRTK.WindowsMixedReality/Packages/manifest.json
- XRTK.WindowsMixedReality/ProjectSettings/ProjectVersion.txt
Implements changes from https://github.com/XRTK/XRTK-Core/pull/157
- Blocked until `com.xrtk.core#0.1.10`
> Updated WMR data provider inspector

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/SpatialObservers/WindowsMixedRealitySpatialMeshObserver.cs
Fixed possible NRE with the mesh object's sharedMesh
> Fixed possible NRE with the mesh object's sharedMesh

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/SpatialObservers/WindowsMixedRealitySpatialMeshObserver.cs
Finishes https://github.com/XRTK/XRTK-Core/pull/179
> added collider display option work

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Inspectors/XRTK.WindowsMixedReality.Inspectors.asmdef
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/XRTK.WindowsMixedReality.asmdef
updated assembly defs to use guids
> updated assembly defs to use guids

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Controllers/WindowsMixedRealityController.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Controllers/WindowsMixedRealityDataProvider.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/package.json
- XRTK.WindowsMixedReality/Packages/manifest.json
Updating with changes required forhttps://github.com/XRTK/XRTK-Core/pull/386
- Requires https://github.com/XRTK/XRTK-Core/pull/386
> Updating with changes required for camera system updates

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Controllers/WindowsMixedRealityController.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Controllers/WindowsMixedRealityDataProvider.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/package.json
- XRTK.WindowsMixedReality/Packages/manifest.json
> Camera system updates

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Inspectors/WindowsMixedRealityDataProviderProfileInspector.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/package.json
- XRTK.WindowsMixedReality/Packages/manifest.json
Continued from https://github.com/XRTK/XRTK-Core/pull/455
Blocked until next release after 455 is merged.
> updated usage of thisProfile to ThisProfile

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Controllers/Hands/WindowsMixedRealityHandControllerDataProvider.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Profiles/WindowsMixedRealityControllerDataProviderProfile.cs
Continued from https://github.com/XRTK/XRTK-Core/pull/476
> Updated windows hand controller data provider

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Controllers/WindowsMixedRealityController.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Inspectors/WindowsMixedRealityDataProviderProfileInspector.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/package.json
- XRTK.WindowsMixedReality/Packages/manifest.json
Updated the profile inspector to align with core changes in https://github.com/XRTK/XRTK-Core/pull/483
> updated profile inspector

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Inspectors/WindowsMixedRealityDataProviderProfileInspector.cs
Continued from https://github.com/XRTK/XRTK-Core/pull/489
> removed profile lock from inspectors

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Controllers/WindowsMixedRealityHandControllerDataProvider.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Controllers/WindowsMixedRealityHandDataConverter.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Extensions/HandJointKindExtensions.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Profiles/WindowsMixedRealityHandControllerDataProviderProfile.cs
Continues from https://github.com/XRTK/XRTK-Core/pull/497
> Change requests/hand tracking

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Controllers/WindowsMixedRealityController.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Controllers/WindowsMixedRealityControllerDataProvider.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Controllers/WindowsMixedRealityHandControllerDataProvider.cs
https://github.com/XRTK/XRTK-Core/pull/501
> added IMixedRealityControllerDataProvider constructor param

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Controllers/WindowsMixedRealityController.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Controllers/WindowsMixedRealityControllerDataProvider.cs
Continued form https://github.com/XRTK/XRTK-Core/pull/505
> added controller data provider reference to the controller

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Inspectors/WindowsMixedRealityControllerDataProviderProfileInspector.cs
Companion PR to https://github.com/XRTK/XRTK-Core/pull/526
> Change requests for controller provider inspectors

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Controllers/WindowsMixedRealityControllerDataProvider.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Controllers/WindowsMixedRealityHandControllerDataProvider.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/SpatialObservers/WindowsMixedRealitySpatialMeshObserver.cs
Left over from https://github.com/XRTK/XRTK-Core/pull/524
> updated data provider constructors

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/DefaultProfiles/WindowsMixedRealityCameraProviderProfile.asset
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Providers/CameraSystem/WindowsMixedRealityCameraDataProvider.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Providers/InputSystem/Controllers/WindowsMixedRealityControllerDataProvider.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Providers/InputSystem/Controllers/WindowsMixedRealityHandControllerDataProvider.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Providers/InputSystem/Controllers/WindowsMixedRealityMotionController.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Providers/SpatialAwarenessSystem/SpatialObservers/WindowsMixedRealitySpatialMeshObserver.cs
https://github.com/XRTK/XRTK-Core/pull/551
> added guid attribute references

- .gitignore
- XRTK.WindowsMixedReality/Assets/XRTK.Generated.meta
- XRTK.WindowsMixedReality/Assets/XRTK.Generated/SymbolicLinkSettings.asset
- XRTK.WindowsMixedReality/Assets/XRTK.Generated/SymbolicLinkSettings.asset.meta
- XRTK.WindowsMixedReality/Assets/XRTK.Generated/WindowsMixedReality.meta
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/package.json
- XRTK.WindowsMixedReality/Packages/manifest.json
- azure-pipelines.yml
- azure_pipelines/common.yml
- azure_pipelines/stages/publish.yml
- azure_pipelines/stages/steps/build-docs.yml
- azure_pipelines/stages/steps/build-unity-player.yml
- azure_pipelines/stages/steps/export-package-seed.yml
- azure_pipelines/stages/steps/install-unity.yml
- azure_pipelines/stages/steps/return-unity-license.yml
- azure_pipelines/stages/steps/run-unity-tests.yml
- azure_pipelines/stages/steps/upm-package-info.yml
- azure_pipelines/stages/unity-build.yml
Modernized the package with core dependency and azure pipelines
- added preview core package dep
- added azure pipelines yaml
> Added preview package capabilities

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Profiles~/Contollers/WindowsMixedRealityControllerDataProviderProfile.asset
Fixed data provider serialization from #80
> fixed data provider serialization

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Providers/InputSystem/Controllers/WindowsMixedRealityMotionController.cs
cleaned up wmr controller a bit
> cleaned up wmr controller a bit

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Extensions/InteractionSourceExtensions.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Extensions/InteractionSourceExtensions.cs.meta
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Providers/Controllers/WindowsMixedRealityControllerDataProvider.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Providers/Controllers/WindowsMixedRealityHandControllerDataProvider.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Utilities/WindowsApiChecker.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Utilities/WindowsApiChecker.cs.meta
https://github.com/XRTK/XRTK-Core/pull/634
> Moved some uwp specific extensions and utilities to the submodule and out of core

- azure_pipelines/stages/publish.yml
- azure_pipelines/stages/steps/build-unity-player.yml
- azure_pipelines/stages/steps/export-package-seed.yml
- azure_pipelines/stages/steps/install-unity.yml
- azure_pipelines/stages/steps/return-unity-license.yml
- azure_pipelines/stages/steps/run-unity-tests.yml
- azure_pipelines/stages/steps/upm-package-info.yml
- azure_pipelines/stages/unity-build.yml
> sync build yaml

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Extensions/InteractionSourceExtensions.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Providers/Controllers/WindowsMixedRealityControllerDataProvider.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Providers/Controllers/WindowsMixedRealityHandControllerDataProvider.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Utilities/WindowsApiChecker.cs
Removed string usages for Windows API Checker
> Improved Windows API Checker

- XRTK.WindowsMixedReality/Packages/manifest.json
- azure_pipelines/stages/steps/install-unity.yml
> fixes module installation

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Profiles~/Contollers/WindowsMixedRealityController/LeftWMRControllerProfile.asset
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Profiles~/Contollers/WindowsMixedRealityController/RightWMRControllerProfile.asset
Updated and resolved WMR controller mappings to the assets within the WMR package.  Was originally still mapped to the SDK versions.
Left and Right controller mapping assets, updated to use input assets within the WMR package
- Fixes: #100
> Fixed WMR input mapping issues

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Editor/Providers/SpatialAwarenessSystem/SpatialObservers/WindowsMixedRealityControllerDataProviderProfileInspector.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Extensions/InteractionSourceExtensions.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Extensions/SpatialInteractionSourceKindExtensions.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Profiles/WindowsMixedRealityControllerDataProviderProfile.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Providers/CameraSystem/WindowsMixedRealityCameraDataProvider.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Providers/Controllers/WindowsMixedRealityControllerDataProvider.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Providers/Controllers/WindowsMixedRealityHandControllerDataProvider.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Providers/Controllers/WindowsMixedRealityMotionController.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Providers/SpatialAwarenessSystem/SpatialObservers/WindowsMixedRealitySpatialMeshObserver.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Utilities/WindowsMixedRealityHandDataConverter.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Utilities/WindowsMixedRealityUtilities.cs
Adds support to projects running 2019.4 LTS with warn as errors in csc.rsp
- https://github.com/XRTK/XRTK-Core/pull/683
> Marked classes as obsolete in 2019.4 LTS

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Providers/BoundarySystem/WindowsMixedRealityBoundaryDataProvider.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/package.json
- XRTK.WindowsMixedReality/Packages/manifest.json
- XRTK.WindowsMixedReality/Packages/packages-lock.json
Changes from https://github.com/XRTK/XRTK-Core/pull/705
> updated the boundary data provider with the latest breaking changes

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Profiles~/Contollers/HandController/Left/LeftWMRHandGripInteractionMappingProfile.asset
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Profiles~/Contollers/HandController/Right/RightWMRHandGripInteractionMappingProfile.asset
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Profiles~/Contollers/WindowsMixedRealityController/Left/GripPressProfile.asset
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Profiles~/Contollers/WindowsMixedRealityController/Right/GripPressProfile.asset
https://github.com/XRTK/SDK/pull/212
> Clean up grip related input actions

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Profiles~/WindowsMixedRealityPlatformConfigurationsProfile.asset
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Providers/BoundarySystem/WindowsMixedRealityBoundaryDataProvider.cs
> fixed missing boundary data provider in platform installation configuration

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/package.json
- XRTK.WindowsMixedReality/Packages/manifest.json
- XRTK.WindowsMixedReality/Packages/packages-lock.json
- XRTK.WindowsMixedReality/ProjectSettings/ProjectVersion.txt
> updated editor to 2019.4.23f1

- .gitignore
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/Providers/Controllers/WindowsMixedRealityControllerDataProvider.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/package.json
- XRTK.WindowsMixedReality/Packages/manifest.json
- XRTK.WindowsMixedReality/Packages/packages-lock.json
Remove glTF loading from WMR package
Supports: https://github.com/XRTK/XRTK-Core/pull/801
for glTF loading on WMR, a custom Visualizer would be needed to load the platform or custom glTF model
> Remove glTF loading from WMR package

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Editor/AssemblyInfo.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Editor/AssemblyInfo.cs.meta
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/AssemblyInfo.cs
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Runtime/AssemblyInfo.cs.meta
Adding compiler definitions for platforms
- https://github.com/XRTK/XRTK-Core/pull/839
> Adding compiler definitions for platforms

- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Profiles~/SpatialAwarenessSystem.meta
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Profiles~/SpatialAwarenessSystem/WindowsMixedRealitySpatialMeshObserverProfile.asset
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Profiles~/SpatialAwarenessSystem/WindowsMixedRealitySpatialMeshObserverProfile.asset.meta
- XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Profiles~/WindowsMixedRealityPlatformConfigurationsProfile.asset
Added WMR spatial mesh observer profile
- https://github.com/XRTK/XRTK-Core/pull/848
> added wmr spatial mesh observer profile
